# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PrismicPractice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PrismicPractice
pod 'Siesta', '~> 1.0'
pod 'Siesta/UI', '~> 1.0'
pod 'Siesta/Alamofire', '~> 1.0'


end
